language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t asifhajiyev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true asifhajiyev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket-name: "elasticbeanstalk-ap-northeast-1-608217597045"
  bucket-path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY